name: Tests

on:
    push: ~
    pull_request: ~

jobs:
    phpunit:
        name: PHPUnit on ${{ matrix.php-versions }} ${{ matrix.composer-flags }}
        runs-on: ubuntu-latest
        continue-on-error: ${{ !matrix.stable }}
        strategy:
            matrix:
                php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
                stable: [true]
                coverage: [true]
                composer-flags: ['']

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: curl, mbstring
                  coverage: xdebug
                  tools: composer:v2

            - run: composer update --no-progress ${{ matrix.composer-flags }}

            - run: vendor/bin/phpunit --testsuite=test --no-coverage
              if: ${{ !matrix.coverage }}

            - run: vendor/bin/phpunit --testsuite=test --coverage-text --coverage-clover=coverage.clover
              if: ${{ matrix.coverage }}
